### ISSUE TITLE
To-Do-List/First

### ISSUE THREAD

**Issue by JaquelineGongora** [JaquelineGongora/Equipo-5#4]
- [x] Product description _(Mauro)._
- [x] Value proposal _(Jaqui)._
- [x] Requirements (RF) _(Jaqui, Mariana, Mauro)._
- [x] Requirements (RNF) _(Jaqui, Mariana, Mauro)._
- [x] Requirements prioritization _(Jaqui)._
- [x] Artifacts (Use Cases) _(Mariana)._
- [x] Abstraction (Class diagram) _(Eduardo, Ricardo)._
- [x] Process description _(Eduardo)._
- [x] Binnacle _(Mariana, Jaqui)._
- [x] Metric _(Mariana)._
- [x] Readme Organization _(Mauro)._
- [x] Requeriments specification _(Eduardo, Ricardo)_
- [x] Video (Audio) _(Mauro, Mar)_
- [x] Video (Presentation) _(Jaqui, Eduardo)_
- [x] Edit Video _(Ricardo)_ 
- [x] Competencies _(Ricardo, Eduardo)_

**Comment by JaquelineGongora** [comment]
Done
